version: "3"
services:
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/sonarr/data:/config
          - /mnt/media/tv:/tv #optional
          - /mnt/media/anime:/anime #optional
          - /mnt/media/cartoons:/cartoons #optional
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 8989:8989
        restart: unless-stopped
    sonarr-anime:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr-anime
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/sonarr-anime/data:/config
          - /mnt/media/tv:/tv #optional
          - /mnt/media/anime:/anime #optional
          - /mnt/media/cartoons:/cartoons #optional
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 8990:8989
        restart: unless-stopped
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/radarr/data:/config
          - /mnt/media/movies:/movies #optional
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 7878:7878
        restart: unless-stopped
    radarr-anime:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr-anime
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/radarr-anime/data:/config
          - /mnt/media/movies:/movies #optional
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 7879:7878
        restart: unless-stopped
    readarr:
        image: lscr.io/linuxserver/readarr:develop
        container_name: readarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/readarr/data:/config
          - /mnt/media/ebooks/readarr:/books #optional
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 8787:8787
        restart: unless-stopped
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/prowlarr/data:/config
        ports:
          - 9696:9696
        restart: unless-stopped
    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/lidarr/data:/config
          - /mnt/media/music/lidarr:/music #optional
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 8686:8686
        restart: unless-stopped
    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/overseerr/config:/config
        ports:
          - 5055:5055
        restart: unless-stopped
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
          - WEBUI_PORT=8080
          - TORRENTING_PORT=6881
        volumes:
          - /docker/qbittorrent/config:/config
          - /mnt/downloads/uTorrent:/downloads #optional
        ports:
          - 8080:8080
          - 6881:6881
          - 6881:6881/udp
        restart: unless-stopped
    sabnzbd:
        image: lscr.io/linuxserver/sabnzbd:latest
        container_name: sabnzbd
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/sabnzbd/config:/config
          - /mnt/downloads/uTorrent:/downloads #optional
          - /mnt/downloads/_TEMP/sabnzbd:/incomplete-downloads
        ports:
          - 8081:8080
        restart: unless-stopped
    tautulli:
        image: lscr.io/linuxserver/tautulli:latest
        container_name: tautulli
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/tautulli/config:/config
        ports:
          - 8181:8181
        restart: unless-stopped
    kavita:
        image: lscr.io/linuxserver/kavita:latest
        container_name: kavita
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/kavita/config:/config
          - /docker/kavita/data:/data
          - /mnt/media/ebooks:/ebooks
        ports:
          - 5000:5000
        restart: unless-stopped
    # jackett:
        # image: lscr.io/linuxserver/jackett:latest
        # container_name: jackett
        # environment:
          # - PUID=1000
          # - PGID=1000
          # - TZ=Asia/Karachi
          # - AUTO_UPDATE=true #optional
        # volumes:
          # - /docker/jackett/data:/config
          # - /docker/jackett/blackhole:/downloads
        # ports:
          # - 9117:9117
        # restart: unless-stopped
    flaresolverr:
        image: 'ghcr.io/flaresolverr/flaresolverr:latest'
        restart: unless-stopped
        environment:
            - LOG_LEVEL=info
        ports:
            - 8191:8191
        container_name: flaresolverr
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/bazarr/config:/config
          - /mnt/media/movies:/movies #optional
          - /mnt/media/tv:/tv #optional
        ports:
          - 6767:6767
        restart: unless-stopped
    tranga-api:
        image: glax/tranga-api:latest
        container_name: tranga-api
        volumes:
          - /mnt/media/ebooks/Library/Manga:/Manga
          - /docker/taranga/data:/usr/share/tranga-api
        ports:
          - "6531:6531"
        restart: unless-stopped
    tranga-website:
        image: glax/tranga-website:latest
        container_name: tranga-website
        ports:
          - "9555:80"
        depends_on: 
          - tranga-api
        restart: unless-stopped
    komga:
        image: gotson/komga
        container_name: komga
        volumes:
          - /docker/bazarr/config:/config
          - /mnt/media/ebooks/Library/Manga:/data
        ports:
          - 25600:25600
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        restart: unless-stopped
    mylar3:
        image: lscr.io/linuxserver/mylar3:latest
        container_name: mylar3
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Karachi
        volumes:
          - /docker/mylar3/config:/config
          - /mnt/media/ebooks/Library/Comics:/comics
          - /mnt/downloads/uTorrent:/downloads
        ports:
          - 8090:8090
        restart: unless-stopped