version: '3'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - data:/home/node/.n8n # Use a named volume instead of bind mount
    restart: unless-stopped
    environment:
      - TZ=Asia/Karachi
      - PUID=1000
      - PGID=1000

volumes:
  data: {} # Define the named volume
